# Generated by Django 5.2.6 on 2025-10-20 05:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('theme', models.CharField(default='dark', max_length=20)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('two_factor_secret', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('enc_default', models.CharField(default='AES-256-GCM', max_length=50)),
                ('stego_default', models.CharField(default='LSB', max_length=50)),
                ('max_size', models.BigIntegerField(default=104857600)),
                ('keep_days', models.IntegerField(default=30)),
            ],
            options={
                'db_table': 'settings',
            },
        ),
        migrations.CreateModel(
            name='UserKeys',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key_name', models.CharField(max_length=100)),
                ('public_key', models.TextField()),
                ('private_key', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_keys',
            },
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('analyzed_filename', models.CharField(max_length=255)),
                ('algorithm', models.CharField(max_length=50)),
                ('probability', models.DecimalField(decimal_places=4, max_digits=5)),
                ('confidence', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('analysis_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'detection',
                'indexes': [models.Index(fields=['user', 'created_at'], name='detection_user_id_d27982_idx')],
            },
        ),
        migrations.CreateModel(
            name='Encryption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('input_filename', models.CharField(max_length=255)),
                ('output_filename', models.CharField(max_length=255)),
                ('algorithm', models.CharField(max_length=50)),
                ('operation', models.CharField(choices=[('encrypt', 'Encrypt'), ('decrypt', 'Decrypt')], max_length=10)),
                ('file_size', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'encryptio',
                'indexes': [models.Index(fields=['user', 'created_at'], name='encryptio_user_id_76897c_idx')],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_original', models.CharField(max_length=255)),
                ('name_stored', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('document', 'Document'), ('other', 'Other')], max_length=10)),
                ('file_size', models.BigIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_encrypted', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'files',
                'indexes': [models.Index(fields=['user'], name='files_user_id_05e794_idx'), models.Index(fields=['uploaded_at'], name='files_uploade_83063c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Steganography',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('carrier_filename', models.CharField(max_length=255)),
                ('data_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('output_filename', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=50)),
                ('operation', models.CharField(choices=[('hide', 'Hide'), ('extract', 'Extract')], max_length=10)),
                ('carrier_size', models.BigIntegerField()),
                ('hidden_data_size', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'steganography',
                'indexes': [models.Index(fields=['user', 'created_at'], name='steganograp_user_id_6ec32e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('operation', models.CharField(choices=[('sign', 'Sign'), ('verify', 'Verify')], max_length=10)),
                ('signature_result', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='steganography_app.userkeys')),
            ],
            options={
                'db_table': 'signature',
                'indexes': [models.Index(fields=['user', 'created_at'], name='signature_user_id_e1bcb2_idx')],
            },
        ),
    ]
