# Generated by Django 5.2.6 on 2025-10-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steganography_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='confidence',
            field=models.CharField(choices=[('low', 'Thấp'), ('medium', 'Trung bình'), ('high', 'Cao')], max_length=10),
        ),
        migrations.AlterField(
            model_name='encryption',
            name='operation',
            field=models.CharField(choices=[('encrypt', 'Mã hóa'), ('decrypt', 'Giải mã')], max_length=10),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(choices=[('image', 'Hình ảnh'), ('audio', 'Âm thanh'), ('video', 'Video'), ('document', 'Tài liệu'), ('other', 'Khác')], max_length=10),
        ),
        migrations.AlterField(
            model_name='signature',
            name='operation',
            field=models.CharField(choices=[('sign', 'Ký'), ('verify', 'Xác thực')], max_length=10),
        ),
        migrations.AlterField(
            model_name='steganography',
            name='operation',
            field=models.CharField(choices=[('hide', 'Ẩn dữ liệu'), ('extract', 'Trích xuất')], max_length=10),
        ),
    ]
