# Generated by Django 5.2.6 on 2025-10-21 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steganography_app', '0002_alter_detection_confidence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('encryption', 'Mã hóa'), ('decryption', 'Giải mã'), ('hide_data', 'Giấu tin'), ('extract_data', 'Trích xuất tin'), ('steganalysis', 'Phân tích tin ẩn'), ('signature', 'Ký số'), ('verification', 'Xác thực')], max_length=20)),
                ('input_filename', models.CharField(max_length=255)),
                ('output_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('algorithm', models.CharField(blank=True, max_length=100, null=True)),
                ('file_size', models.BigIntegerField()),
                ('status', models.CharField(choices=[('success', 'Thành công'), ('failed', 'Thất bại'), ('processing', 'Đang xử lý')], default='processing', max_length=15)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('execution_time', models.FloatField(blank=True, null=True)),
                ('parameters', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'activity_logs',
            },
        ),
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_original', models.CharField(max_length=255)),
                ('name_stored', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('image', 'Hình ảnh'), ('audio', 'Âm thanh'), ('video', 'Video'), ('document', 'Tài liệu'), ('encrypted', 'File mã hóa'), ('stego', 'File chứa tin ẩn'), ('other', 'Khác')], max_length=15)),
                ('file_source', models.CharField(choices=[('original', 'File gốc'), ('encrypted', 'File mã hóa'), ('decrypted', 'File giải mã'), ('stego', 'File chứa tin ẩn'), ('extracted', 'File trích xuất')], default='original', max_length=15)),
                ('file_size', models.BigIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'user_files',
            },
        ),
        migrations.RemoveIndex(
            model_name='file',
            name='files_user_id_05e794_idx',
        ),
        migrations.RemoveIndex(
            model_name='file',
            name='files_uploade_83063c_idx',
        ),
        migrations.RenameIndex(
            model_name='encryption',
            new_name='encryption_user_id_9c8181_idx',
            old_name='encryptio_user_id_76897c_idx',
        ),
        migrations.RemoveField(
            model_name='file',
            name='is_encrypted',
        ),
        migrations.AddField(
            model_name='encryption',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encryption',
            name='execution_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encryption',
            name='key_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encryption',
            name='mode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='encryption',
            name='parameters',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='file_source',
            field=models.CharField(choices=[('original', 'File gốc'), ('encrypted', 'File mã hóa'), ('decrypted', 'File giải mã'), ('stego', 'File chứa tin ẩn'), ('extracted', 'File trích xuất')], default='original', max_length=15),
        ),
        migrations.AddField(
            model_name='file',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='encryption',
            name='algorithm',
            field=models.CharField(choices=[('AES-128-GCM', 'AES-128-GCM'), ('AES-192-GCM', 'AES-192-GCM'), ('AES-256-GCM', 'AES-256-GCM'), ('AES-128-CBC', 'AES-128-CBC'), ('AES-192-CBC', 'AES-192-CBC'), ('AES-256-CBC', 'AES-256-CBC'), ('XChaCha20-Poly1305', 'XChaCha20-Poly1305'), ('Ascon128', 'Ascon-128'), ('Ascon128a', 'Ascon-128a'), ('Ascon80pq', 'Ascon-80pq')], max_length=50),
        ),
        migrations.AlterField(
            model_name='encryption',
            name='output_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(choices=[('image', 'Hình ảnh'), ('audio', 'Âm thanh'), ('video', 'Video'), ('document', 'Tài liệu'), ('encrypted', 'File mã hóa'), ('stego', 'File chứa tin ẩn'), ('other', 'Khác')], max_length=15),
        ),
        migrations.AddIndex(
            model_name='encryption',
            index=models.Index(fields=['algorithm', 'operation'], name='encryption_algorit_0f7dd0_idx'),
        ),
        migrations.AlterModelTable(
            name='encryption',
            table='encryption',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='file',
            name='activity_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='steganography_app.activitylog'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['user', 'uploaded_at'], name='files_user_id_bca975_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['file_type', 'file_source'], name='files_file_ty_bee0a9_idx'),
        ),
        migrations.AddField(
            model_name='userfile',
            name='activity_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='steganography_app.activitylog'),
        ),
        migrations.AddField(
            model_name='userfile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', 'created_at'], name='activity_lo_user_id_d23b30_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['activity_type', 'status'], name='activity_lo_activit_f1c8f0_idx'),
        ),
        migrations.AddIndex(
            model_name='userfile',
            index=models.Index(fields=['user', 'uploaded_at'], name='user_files_user_id_2287b0_idx'),
        ),
        migrations.AddIndex(
            model_name='userfile',
            index=models.Index(fields=['file_type', 'file_source'], name='user_files_file_ty_5d5566_idx'),
        ),
    ]
