# Generated by Django 5.2.6 on 2025-10-22 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steganography_app', '0003_activitylog_userfile_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
