# Generated by Django 5.2.6 on 2025-10-28 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steganography_app', '0005_activitylog_ip_address_activitylog_session_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercertificate',
            name='user',
        ),
        migrations.AddField(
            model_name='userkeys',
            name='algorithm',
            field=models.CharField(choices=[('AES-256-GCM', 'AES-256-GCM'), ('XChaCha20-Poly1305', 'XChaCha20-Poly1305'), ('Ascon128a', 'Ascon128a'), ('X25519', 'X25519'), ('Kyber1024', 'Kyber1024')], default='AES-256-GCM', max_length=50),
        ),
        migrations.AddField(
            model_name='userkeys',
            name='is_exportable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userkeys',
            name='key_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userkeys',
            name='key_hash',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='userkeys',
            name='key_type',
            field=models.CharField(choices=[('symmetric', 'Đối xứng'), ('asymmetric', 'Bất đối xứng')], default='symmetric', max_length=15),
        ),
        migrations.AddField(
            model_name='userkeys',
            name='last_used',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userkeys',
            name='public_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='userkeys',
            index=models.Index(fields=['user', 'key_type', 'is_active'], name='user_keys_user_id_96615d_idx'),
        ),
        migrations.DeleteModel(
            name='UserCertificate',
        ),
    ]
