# Generated by Django 5.2.6 on 2025-10-28 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steganography_app', '0006_remove_usercertificate_user_userkeys_algorithm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCertificate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('certificate_name', models.CharField(max_length=255)),
                ('certificate_data', models.TextField()),
                ('private_key', models.TextField()),
                ('public_key', models.TextField()),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'user_certificates',
            },
        ),
        migrations.RemoveIndex(
            model_name='userkeys',
            name='user_keys_user_id_96615d_idx',
        ),
        migrations.RemoveField(
            model_name='userkeys',
            name='algorithm',
        ),
        migrations.RemoveField(
            model_name='userkeys',
            name='is_exportable',
        ),
        migrations.RemoveField(
            model_name='userkeys',
            name='key_data',
        ),
        migrations.RemoveField(
            model_name='userkeys',
            name='key_hash',
        ),
        migrations.RemoveField(
            model_name='userkeys',
            name='key_type',
        ),
        migrations.RemoveField(
            model_name='userkeys',
            name='last_used',
        ),
        migrations.AlterField(
            model_name='userkeys',
            name='public_key',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='usercertificate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
