# Generated by Django 5.2.6 on 2025-10-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steganography_app', '0007_usercertificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='save_activities',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='save_files',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='save_keys',
            field=models.BooleanField(default=True),
        ),
    ]
