# Generated by Django 5.2.6 on 2025-11-14 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steganography_app', '0008_usersettings_save_activities_usersettings_save_files_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encryption',
            name='user',
        ),
        migrations.RemoveField(
            model_name='steganography',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usercertificate',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='user',
        ),
        migrations.DeleteModel(
            name='Detection',
        ),
        migrations.DeleteModel(
            name='Encryption',
        ),
        migrations.DeleteModel(
            name='Steganography',
        ),
        migrations.DeleteModel(
            name='UserCertificate',
        ),
        migrations.DeleteModel(
            name='UserSettings',
        ),
    ]
