# Generated by Django 5.2.6 on 2025-11-22 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steganography_app', '0010_customuser_groups_customuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='two_factor_secret',
        ),
    ]
