# Generated by Django 5.2.6 on 2025-11-25 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steganography_app', '0011_remove_customuser_two_factor_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('save_keys', models.BooleanField(default=True)),
                ('save_files', models.BooleanField(default=True)),
                ('save_activities', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_settings',
            },
        ),
    ]
