# Generated by Django 5.2.6 on 2025-12-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steganography_app', '0012_usersettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userkeys',
            name='user',
        ),
        migrations.AlterField(
            model_name='userfile',
            name='file_source',
            field=models.CharField(choices=[('other', 'File khác'), ('encrypted', 'File mã hóa'), ('stego', 'File chứa tin ẩn')], default='other', max_length=15),
        ),
        migrations.AlterField(
            model_name='userfile',
            name='file_type',
            field=models.CharField(choices=[('image', 'Hình ảnh'), ('audio', 'Âm thanh'), ('document', 'Tài liệu'), ('encrypted', 'File mã hóa'), ('stego', 'File chứa tin ẩn'), ('other', 'Khác')], max_length=15),
        ),
        migrations.DeleteModel(
            name='Signature',
        ),
        migrations.DeleteModel(
            name='UserKeys',
        ),
    ]
