# Generated by Django 5.2.6 on 2025-12-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steganography_app', '0013_remove_userkeys_user_alter_userfile_file_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='save_keys',
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('encryption', 'Mã hóa'), ('decryption', 'Giải mã'), ('hide_data', 'Giấu tin'), ('extract_data', 'Trích xuất tin')], max_length=20),
        ),
    ]
