"""
Django settings for steganography_project project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
# 1. Đường dẫn cơ bản của dự án
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 2. Cấu hình bảo mật và debug
SECRET_KEY = 'django-insecure-a_6#hfi(3+tic47=16_5^-7b*knh#5%0sdn0mucht5dww@6aft'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = []

# 3. Cài đặt ứng dụng
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Ứng dụng tùy chỉnh
    'steganography_app',
    
    # django-allauth
    'django.contrib.sites',  # bắt buộc
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',  # đăng nhập bằng Google
]

SITE_ID = 1  # Bắt buộc cho django-allauth

# 4. Cấu hình middleware
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

# 5. Cấu hình URL và template
ROOT_URLCONF = 'steganography_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'steganography_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# 6. Cấu hình cơ sở dữ liệu

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "ct492",
        "USER": "root",
        "PASSWORD": "130104",
        "HOST": "localhost",
        "PORT": "3307",
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'charset': 'utf8mb4',
        }
    }
}

# 7. Cấu hình xác thực và mật khẩu
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# 8. Cấu hình thời gian
LANGUAGE_CODE = 'vi'
TIME_ZONE = 'Asia/Ho_Chi_Minh'

# 9. Cấu hình tài nguyên tĩnh và media
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
os.makedirs(os.path.join(MEDIA_ROOT, 'encrypted_files'), exist_ok=True)
# Thư mục lưu file người dùng
USER_FILES_ROOT = os.path.join(MEDIA_ROOT, 'user_files')

# 10. Xác thực người dùng 
AUTH_USER_MODEL = 'steganography_app.CustomUser'

#Cấu hình xác thực:
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  # đăng nhập truyền thống
    'allauth.account.auth_backends.AuthenticationBackend',  # allauth
]

# URL chuyển hướng authentication
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = 'dashboard'  # Sau khi đăng nhập
LOGOUT_REDIRECT_URL = 'home'      # Sau khi đăng xuất

# 11. Cấu hình Email 
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'tinhb2203743@student.ctu.edu.vn'
EMAIL_HOST_PASSWORD = 'kyvc qdhu qngu riin'

# Cấu hình hiển thị email
DEFAULT_FROM_EMAIL = 'SecureMedia <tinhb2203743@student.ctu.edu.vn>'
SERVER_EMAIL = 'SecureMedia <tinhb2203743@student.ctu.edu.vn>'

# 12. Bảo mật và CSRF

# Cấu hình Session
# SESSION CONFIG
SESSION_COOKIE_AGE = 300               # 3 phút hết hạn
SESSION_SAVE_EVERY_REQUEST = True        # reset khi có thao tác
SESSION_EXPIRE_AT_BROWSER_CLOSE = True   # đóng trình duyệt = logout
SESSION_COOKIE_SECURE = False            # để True khi lên HTTPS
SESSION_COOKIE_HTTPONLY = True
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_NAME = 'securemedia_sessionid'
CSRF_USE_SESSIONS = False

# Cấu hình CSRF
CSRF_COOKIE_SECURE = False  # Đặt True khi dùng HTTPS (production)
CSRF_COOKIE_HTTPONLY = True  # Bảo mật CSRF cookie
CSRF_TRUSTED_ORIGINS = []  # Thêm domain trusted trong production
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Auto-logout configuration
AUTO_LOGOUT = {
    'IDLE_TIME': 180,  # 3 phút không activity
    'REDIRECT_TO': '/accounts/login/',
    'MESSAGE': 'Phiên đăng nhập đã hết hạn. Vui lòng đăng nhập lại.',
}

# Định dạng file được phép upload
ALLOWED_FILE_TYPES = [
    'image/png', 'image/jpeg', 'image/bmp', 'image/bmp',
    'audio/wav', 'audio/mpeg', 'audio/mp3', 
    'video/mp4', 'video/avi', 'video/mkv',
    'text/plain', 'application/octet-stream',
    'application/zip', 'application/x-rar-compressed',
]

# 14. Cấu hình mặc định
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#15. Cấu hình Django-Allauth - Xác thực người dùng 
ACCOUNT_AUTHENTICATION_METHOD = "email" # Phương thức xác thực
ACCOUNT_EMAIL_REQUIRED = True # Bắt buộc phải có email khi đăng ký tài khoản
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_USER_MODEL_USERNAME_FIELD = "username" #Tên field trong User model được sử dụng làm username
ACCOUNT_EMAIL_VERIFICATION = "optional"
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_LOGOUT_REDIRECT_URL = 'home'
ACCOUNT_LOGIN_REDIRECT_URL = 'dashboard'